# The URL the site will be built for
base_url = "https://c7a6.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

default_language = "en"
theme = "zola-bearblog"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
date_format = "%Y-%m-%d"

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

